sudo: false
language: node_js
node_js:
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
before_install:
  - "nvm install-latest-npm"
before_script:
  - 'if [ -n "${ESLINT-}" ]; then yarn add --dev "eslint@${ESLINT}" ; fi'
script:
  - 'if [ -n "${TEST-}" ]; then yarn test ; fi'
env:
  global:
    - TEST=true
  matrix:
    - ESLINT=5
    - ESLINT=4
    - ESLINT=3
matrix:
  fast_finish: true
  include:
    - node_js: "lts/*"
  allow_failures:
    - env: ESLINT=5
